### PR TITLE
New/add custom text input to invoice

### PR DESCRIPTION
**Pull request by RatulHasan**
This PR will fix [this issue](https://github.com/wp-erp/erp-pro/issues/151)

Screenshot 2023-05-17 at 7 34 36 PM

Screenshot 2023-05-17 at 7 42 04 PM

### CODE REVIEW

**Comment by saiftheboss7** [comment]
Instead of "Custom text" in the PDF, rename it as "Additional Notes"

**Comment by RatulHasan** [comment]
> Instead of "Custom text" in the PDF, rename it as "Additional Notes"

@saiftheboss7 
This PR is created as per the mockup. If you wish to refactor this, I'll gladly do this.

**Comment by RatulHasan** [comment]
> @RatulHasan
> 
> https://github.com/wp-erp/wp-erp/blob/3ec2f9bc186089a24484d23e3b21737d81e8a97a/modules/accounting/assets/src/admin/components/transactions/sales/InvoiceSingleContent.vue#L119
> 
> In this line is missing `, 'erp'` or am I wrong?
> 
> Thanks.
> 
> P.S. Could you please take a look at my PR and my Issues Report?
> 
> Thank you.

@DAnn2012 ,
In translation first should be the text and the second should be the text domain. And yes, you are right.
Make all the translation-related changes in one PR, and labeled it as `Need dev review`. I'll take care of this in the next release, InshaAllah

**Comment by saiftheboss7** [comment]
@RatulHasan Yes please

**Pull request merged**
