### PR TITLE
Remove contact subscriber hash

### PR DESCRIPTION
**Pull request by iwassa-ahmedkandel**
Fix: #500 as installs from v1.1.17 to v1.2.3 has no 'Hash' colmun in
'erp_crm_contact_subscriber' table which generates error, and as from
v1.2.2 'Hash' colmun is not needed anymore and replaced by people meta
this PR to remove traces of hash.

### CODE REVIEW

**Comment by ediamin** [comment]
@iwassa-ahmedkandel the hash column in `erp_crm_contact_subscriber` is not deprecated. We are using it in our ERP Email Campaign right now. This is a people property which is related to a contact group. The hash in people_meta is independent of it and you can use it to hide people id in front-end or anywhere else. Thanks.

**Comment by iwassa-ahmedkandel** [comment]
@ediamin thanks  alot for explanation, please if you could add "ALTER TABLE ADD `hash`" in next update script because from v1.1.17 till you fixed it 375ab19 all new installations don't have this colmun in DB and it through error.
Thanks again.

**Comment by ediamin** [comment]
Are you sure new installations don't have this column? Actually I've added the updater in v1.1.17, take a look it [in here ](https://github.com/wp-erp/wp-erp/commit/09fe314900c9b26f55736a8118f0ccbadf66f642#diff-46321b17ca531b67321634550a1d4fcaR17)

**Comment by iwassa-ahmedkandel** [comment]
Yes i am sure, all installs before **v1.1.17** got **updated and fixed** by the updater in v1.1.17 on **30/03/2017**.
While still the column is missing in `class-install.php` untill you fixed it here 375ab19 at **v1.2.3** on **10/08/2017**.
Between those two versions all new installs does not have `hash` column, you can check by installing any of the following versions: v1.1.18 , v1.1.9 , v1.2.0 , v1.2.1 , v1.2.2 
I have tested v1.2.2 and can confirm this issue. my proposal to fix is to reinclude in coming version updater to fix older versions and as it is already in `class-install.php` now new installs are covered.
Thanks.

**Comment by ediamin** [comment]
@iwassa-ahmedkandel thanks for pointing this our. I'll add an updater for next version.

**Pull request closed without merging**
