### PR TITLE
Fix secuirty issue make wp user

### PR DESCRIPTION
**Pull request by iwassa-ahmedkandel**
Managers that can create wp user from contact can assign to him any role including administrator which has higher capabilities that the manager who created the user. Could be used to hack the WordPress instance.

### CODE REVIEW

**Comment by iwassa-ahmedkandel** [comment]
Hi,
Any news regarding this request ?
Thanks

**Comment by ediamin** [comment]
Hi @iwassa-ahmedkandel sorry for the late reply. Actually, we were discussing regarding this issue. We have decided that, we should only unset the administrator role instead of keeping only subscriber role. Since WP doesn't provide any hierarchical role array/object, we don't know which roles are higher than CRM Manager. So, it is better to remove the administrator role only and we will add a new filterable function `erp_get_editable_roles` which will provide logical roles that an admin or crm manager can attach to any crm contact. So, if you personally think that, you should only use the subscriber role, then please use that filter. I'll comment again here after we push the new function.

Thank you very much.

**Comment by iwassa-ahmedkandel** [comment]
Hi @ediamin good idea the `erp_editable_roles` filter while the make_wp_user function is only called for customers not employee so by logic customers wouldn't have (Employee, Manager, Agent, ...) roles instead Subscriber role is enough then if needed admin can proceed to upgrade them though normal WP mechanism.
Thanks.

**Comment by ediamin** [comment]
Hi take a look at this commit https://github.com/wp-erp/wp-erp/commit/e508dd2198e266a28d621d1ed45dcd1908f30b2e

We will use it this way for now. May be we'll change the logic later. 

Thanks.

**Comment by iwassa-ahmedkandel** [comment]
Thanks

**Pull request closed without merging**
